### ISSUE TITLE
TODO: Find placeholders for Badlands creatures

### ISSUE THREAD

**Issue by mindphluxnet** [The-Alpha-Project/alpha-core#1024]
**Describe what needs to be implemented or enhanced**
Badlands has several creature groups with missing models:

- Kargath: almost all NPCs lack models
- gnome quest hub: all of them
- all Shadowforge dwarves
- Theldurin the Lost

Paging @geo-tp once more.

**Comment by geo-tp** [comment]
I already changed some here : https://github.com/The-Alpha-Project/alpha-core/pull/545.


Here is what I skipped because of evidence : 

2785 Theldurin The Lost
-------------------

Probably dwarf placeholder 2584

![Capture d’écran_2023-03-23_23-11-54](https://user-images.githubusercontent.com/72315006/227376763-e6efb0a6-b4cc-4188-926e-9ecc5a81d59c.png)

2910 Prospector Ryedol
----------------

Probably dwarf placeholder 2584

Kargath
---------

As for Grom Gol, Dustwallow march village, and Stonard, orc should probably use default placeholder too

![Capture d’écran_2023-03-23_23-11-23](https://user-images.githubusercontent.com/72315006/227376649-5237a4a1-bf49-40d0-80b7-d0e6aa67a7a7.png)

2908 Grawl (male)
1407 Sranda (female)
5396 Neeka Bloodscar (female)



Gnomes
-----------

2921 Lotwill
2920 Lucien Tosselwrench

![Capture d’écran_2023-03-23_23-11-38](https://user-images.githubusercontent.com/72315006/227376729-85c157e2-447d-4ee9-841b-cbce8604bd5a.png)

Known to be a placeholder, also used in Thousand Needles

or old gnomes like Ruppo 

![Capture d’écran_2023-03-23_23-29-32](https://user-images.githubusercontent.com/72315006/227379068-a550c347-cbe2-4bb6-a73d-8a4b1490a5ec.png)

![image](https://user-images.githubusercontent.com/72315006/227379262-49886f14-8870-42af-8a7b-2d1cb2d92483.png)



Shadowforge
---------------

Could be Dark iron mobs, could be dwarf placeholder or even more

for reference, here are all dark iron mobs : 
![Capture d’écran_2023-03-23_22-57-22](https://user-images.githubusercontent.com/72315006/227377017-3e563bca-12be-4893-bad1-988d5354a34a.png)

![Capture d’écran_2023-03-23_22-58-11](https://user-images.githubusercontent.com/72315006/227377037-a82286fe-6f59-4862-a680-12251981bb0f.png)

![Capture d’écran_2023-03-23_23-01-00](https://user-images.githubusercontent.com/72315006/227377050-f8a85f12-a917-4e5c-a523-d69ce34745fe.png)

![Capture d’écran_2023-03-23_23-01-12](https://user-images.githubusercontent.com/72315006/227377132-27f305b1-34e2-4f5b-8131-630e86fcc654.png)

![Capture d’écran_2023-03-23_23-01-28](https://user-images.githubusercontent.com/72315006/227377146-64a86ac7-de07-4290-ba7e-0115f550e1b9.png)

![Capture d’écran_2023-03-23_23-01-48](https://user-images.githubusercontent.com/72315006/227377157-228b7fb3-365b-4e96-ba7c-ad5337b38821.png)

![Capture d’écran_2023-03-23_23-02-05](https://user-images.githubusercontent.com/72315006/227377171-efdcf9c4-98f7-411b-86f7-ea3333b63050.png)
