### ISSUE TITLE
TODO: Find display_ids for Thousand Needles NPCs

### ISSUE THREAD

**Issue by mindphluxnet** [The-Alpha-Project/alpha-core#1035]
**Describe what needs to be implemented or enhanced**
There are a few locations in Thousand Needles with NPCs that have no display_id:
- -5185.9423828125 -2805.562255859375 -8.236062049865723 1 - Dorn Plainstalker
- -5846.5498046875 -3414.1201171875 -51.055198669433594 1 - Horde camp
- -5467.9384765625 -2445.765869140625 89.35128784179688 1 - Freewind Post

**Comment by geo-tp** [comment]
All NPCs with evidence were resolved here https://github.com/The-Alpha-Project/alpha-core/pull/387 : 

Since we don't have much more evidence, we could try to use standard placeholders if @GrenderG want it.

Standard placeholders seem to be the best choice to use when we don't have any data.

![stdph](https://user-images.githubusercontent.com/72315006/227721640-732b8633-017b-4ed8-ac9e-d4f72dfdf9f1.png)

We were able to see that all the models other than human are for the most part solved by the standard placeholders
especially in an unfinished zone like Thousand Needles which has a lot of placeholders (race area for example)

We have many examples : Burning blade, Dragonmaw, Dwarf pilots, Gromgoll troll, Gromgoll orc, dwarf flymaster...

Dorn Plainstalker
----------------------

We have a screenshot showing Dorn with a non final model (cant found it), very close from Tauren placeholder

![c27](https://user-images.githubusercontent.com/72315006/227721628-e8024112-9d4d-4f5b-9b3b-968b3bef05b8.jpg)
![taurenplaceholder png](https://user-images.githubusercontent.com/72315006/227721667-79bdf209-adc5-4e0b-8395-6b97d8a7b256.png)

2986 Dorn plainstalker 2578

Horde Camp
------------------

We could use the standard orc  that we know (1139, 2576) or another known placeholder sometimes used for high entry orc (3508).

![orcpl](https://user-images.githubusercontent.com/72315006/227722145-1c76a007-af79-4bb0-9c22-f7b6805a92bb.png)

![orcplaceholder](https://user-images.githubusercontent.com/72315006/227721712-40a645ed-bfd3-4104-8983-c3f1f2de2e50.png)

![Capture d’écran_2023-03-25_01-45-41](https://user-images.githubusercontent.com/72315006/227721723-e7e45dfb-9487-403a-985f-eb1f06e7a8d4.png)

Since we see way more 2576 than 3508,  it's probably less risky to chose the standard one.

4483 Motktar krin 2576 OR 3508
4545 Nag'zehn 2576 OR 3508
4546 bor'zhen 2576 OR 3508
4547 Tarkreu Shadowstalker 2576 OR 3508

Since War party Kodo model doesnt exist, we could use same color variation

![Capture d’écran_2023-03-25_00-47-08](https://user-images.githubusercontent.com/72315006/227721735-288e91ee-c06e-4cbc-a230-9bdf39fec55f.png)


5523 War Party Kodo 1308 & 1309 (big)

If Kodo seems too big, we could use

5523 War Party Kodo 1452 & 1453 (smaller)

Freewind Post
--------------------

We use tauren/orc placeholder for them as well

4875 Turhaw 2576 OR 3508
4876 jawn highmesa 2578
4877 Jandia 2579
4878 montarr 2578
