### ISSUE TITLE
TODO: Find remaining display_ids for Desolace

### ISSUE THREAD

**Issue by mindphluxnet** [The-Alpha-Project/alpha-core#1039]
**Describe what needs to be implemented or enhanced**
Desolace has some NPCs missing display_ids:
- -1948.632080078125 1263.62548828125 92.1963882446289 1 - Khan Jehn
- -795.566 934.17 90.5846 1 - Khan Dez'hepah
- -1355.90966796875 2936.725341796875 113.46289825439453 1 - Maraudine Marauder
- -1334.39453125 1704.7894287109375 89.05329895019531 1 - Ghostwalker Post (2 NPCs)

**Comment by geo-tp** [comment]
Same as #1035 for standard placeholder.
Some models were already resolved with evidence here https://github.com/The-Alpha-Project/alpha-core/pull/527


Centors
---------------

Besides color variation, there is only one centaur model for 0.5.3
Most of centaurs in Desolace use brown models and 1349 is the highest scaled model that seem fit for named.


4658 Maraudine Stormer 1348
4659 Maraudine Marauder 1348
5600 Khan Dez'hepah 1349
5601 Khan Jehn 1349


Ghostwalker Post 
-------------

Since it's a very unfinished zone at this point, standard placeholders seem the right choice.
As we know, high entry orc could use the second placeholder 3508, even if standard one seems fit more.

![orcplaceholder](https://user-images.githubusercontent.com/72315006/227723357-db419b51-aa68-4d97-9ff8-9634c95b121a.png)

![Capture d’écran_2023-03-25_01-45-41](https://user-images.githubusercontent.com/72315006/227723361-a3b64359-a119-4161-a5d8-978d0a1a0836.png)


5395 Felgur Twocuts 2576 OR 3508
5412 Gurda Wildmane 2579

We also know for sure that standard orc is already used for Burning blade mobs around in Desolace

blizzlike Burning Blade unused mob
![185723404-300670c3-f481-49d4-82ac-1ae8120436e6](https://user-images.githubusercontent.com/72315006/227723177-d8c8cb28-462c-4c52-ad98-00fb0e40e35f.png)


Hyena
-------

Used by another hyena mob in Desolace

4688 Bonepaw Hyena 2716
