### ISSUE TITLE
TODO: Find remaining display_ids for Arathi Highlands

### ISSUE THREAD

**Issue by mindphluxnet** [The-Alpha-Project/alpha-core#1046]
**Describe what needs to be implemented or enhanced**
Only two NPCs missing their display_id in Arathi:
- -987.6513061523438 -3546.007080078125 57.576805114746094 0 - Zaruk
- -1720.5946044921875 -1536.84716796875 55.78356170654297 0 - Or'kalar

**Comment by geo-tp** [comment]
Or'Kalar
-----------
Since he is a named we could use 1054 with scale 1.3 (also used by 2 another named), there is only one ogre model so only color variation could be wrong

Zaruk
--------
standard orc if we want to resolve it without evidence

his new model will be added probably in 0.5.4, so it would be hard to find a screenshot of him
![Capture d’écran_2023-03-25_20-48-28](https://user-images.githubusercontent.com/72315006/227738458-eda4502b-8e3e-4656-a290-3e0a867bc4de.png)
