### ISSUE TITLE
The Barren's Horde Guards are dabiri cubes

### ISSUE THREAD

**Issue by Yushe** [The-Alpha-Project/alpha-core#322]
**Describe the bug**
The horde guard NPCs that are dotted around the barrens use a display id that is 100 or so digits higher than what is available in 0.5.3.
They need to be updated to use the same display ids which Orgrimmar Grunts & Razor Hill Grunts use.

**NPC Info**
Entry: 3501
Display ID: 4261

**Comment by GrenderG** [comment]
Do we have any screenshot of them?

**Comment by Yushe** [comment]
Sorry I forgot to mention when rewritting this issue that I looked around in the image archive but I unfortunately couldn't find any old screenshots that featured the guards before they changed to a higher display id.

My only theory is that since both the Orgrimmar Grunts & Razor Hill Grunts got changed to an earlier model then they were probably using that same display id from the Horde Guard in the barrens.
If evidence to the contrary is found that would be great.

**Comment by Daribon** [comment]
I will probably be able to find it.

**Comment by geo-tp** [comment]
Crossroads guards have 4 models : Tauren male/female, Orc male/female
![588607-534914_20040805_019](https://user-images.githubusercontent.com/72315006/182482636-eae54a6c-48be-4396-963a-3f554d15cab5.jpg)

Only orc guards display_id not used by a named NPC are : 1908 (female), 1909 (male). It's actually Razorhill/Orgrimmar guards.
![1908](https://user-images.githubusercontent.com/72315006/182482751-df11ec24-98f3-4426-a41c-30c145445e4d.png)
![1909](https://user-images.githubusercontent.com/72315006/182482758-90588903-5874-4d36-9f2a-1e168864b188.png)

I founded that there are 2 taurens unused guards models : 3772 (female), 3773 (male)
![3772](https://user-images.githubusercontent.com/72315006/182483216-3ecfef25-4e24-47ac-81c6-5eb2b2796650.png)
![3773](https://user-images.githubusercontent.com/72315006/182483222-482f8a42-0a7d-413e-8b8f-ccf8eaaa61e7.png)

![Capture d’écran_2022-08-03_00-17-05](https://user-images.githubusercontent.com/72315006/182483264-76e42bae-ced7-4d75-af8a-188d8629f0ad.png)

Since there are no guards in Narache, they probably reused models for crossroads guards.

**Comment by geo-tp** [comment]
This issue can be close, guards have display_id now.
