### ISSUE TITLE
Abilities don't take weapon skill into account

### ISSUE THREAD

**Issue by Dovvah** [The-Alpha-Project/alpha-core#333]
At low weapon skill it should be pretty much impossible to hit, which is true for auto attacks but my abilities hit 100% of the time

video https://www.youtube.com/watch?v=nKzQIcQfKWY

**Comment by Fluglow** [comment]
#238 - spells (including abilities) can only result in a hit.

**Comment by GizzleBizzle** [comment]
I think it is because skill proficiency isn't taken into account when determining if the skill lands or not.

Weapon autoattacks are connected to the skill of the weapon used and it works fine.
Abilities and Spells each have their proficiency tag in their ingame tooltips (Like Fireball spell is a part of Fire Magic proficiency) and the game seems to skip it even If I learn the proficiency manually via command.
