### ISSUE TITLE
Teleported when stepping off elevators.

### ISSUE THREAD

**Issue by Dovvah** [The-Alpha-Project/alpha-core#342]
**Describe the bug**
Sometimes when I step off of the Ironforge elevator I get teleported away, sometimes multiple times, then back to the elevator. So far I've been unable to reproduce this consistently it's happened 2x in about 10 attempts. 

Video: https://www.youtube.com/watch?v=RAsGBmWhjhI

**Comment by Daribon** [comment]
I recall having the same issue at both Undercity and Ironforge elevator over 6 months ago, at separate times.
Since I haven't been able to reproduce it since then, I do now know what could possibly cause it.

**Comment by GrenderG** [comment]
Yeah this is a known issue, I'm not entirely sure if it's a client issue or a server one since it's the client who's actually sending movement packets with wrong coordinates, the teleport back you mention is my server side hackfix to move you back to the elevator if it detects a huge coordinate desync. Also, I remember seeing screenshots showing messages from Blizzard advising players to not use elevators since they could kill them.

**Comment by Daribon** [comment]
I've managed to reproduce the issue with 100% success.
1. Walk onto Ironforge elevator
2. Let it start moving and do not move whatsoever.
3. Let the elevator stop and start moving
4. Your character will be teleported.

How not to reproduce:
1. Walk onto Ironforge elevator
2. Let the elevator start moving and move your character while the elevator is moving.
3. Let the elevator stop and start moving
4. Your character will not be teleported.

Exactly the same thing can reproduced when using Undercity elevator

**Comment by mindphluxnet** [comment]
Can be closed, elevators work fine now.
