### ISSUE TITLE
Quest: The Stolen Tome

### ISSUE THREAD

**Issue by dirtbikercj** [The-Alpha-Project/alpha-core#405]
**Describe the bug**

The quest 'The Stolen Tome' is the warlock's summon imp quest in Northshire. The 'stolen book' game object that spawns the required item 'Powers of the void' spawns in presumably the wrong location around a campfire. The quest text states "They have it hidden at their tent in the Vineyards" 

**Steps to reproduce**
1. Take quest 'The Stolen Tome'
2. Goto  `.port -8957.04 -432.748 64.7194 0`
3. loot book

**Expected behavior**
Book should spawn at tent

**Screenshots**

Current Position in game world
![Current POS + quest text](https://user-images.githubusercontent.com/62989449/183272508-2fbfb625-eef2-4ea3-9a6f-4acd1ec7a2f4.png)
Expected position in game world
![image](https://user-images.githubusercontent.com/62989449/183272539-9364c279-6fbe-4ba1-9001-8a6ed4257dea.png)

**Comment by sadpanda353** [comment]
you are sure it was not just that way in 0.5.3 ?

**Comment by GrenderG** [comment]
Notes about this quest:

- It seemed to exist in 0.5.3 but probably the actual requirement was not this book as the entry is slightly high for what we think is the maximum entry in 0.5.3.
- Drusilla La Salle was maybe named Meritt Herrion according to https://web.archive.org/web/20040711223019/http://wow.allakhazam.com/db/quest.html?wquest=1598
- Also according to Allakhazam it gave you [an scroll that taught you to summon the Imp](https://classic.wowhead.com/item=6516/imp-summoning-scroll), instead of the imp directly.

Last note might apply to quest for other races.

**Comment by dirtbikercj** [comment]
0.5.5 patch notes indicate the addition of warlock specific quests. [https://wowpedia.fandom.com/wiki/Patch_0.5.5](url) 

This quest and other races warlock quests if they exist likely needs removed

**Comment by GrenderG** [comment]
Good catch, most likely no quest to Summon Imp existed in 0.5.3 yet. Related https://github.com/The-Alpha-Project/alpha-core/issues/398.

**Comment by GrenderG** [comment]
Note: these quests have been remove from the game so this gameobject (not sure if others) need to be ignored too.

**Comment by dirtbikercj** [comment]
> Note: these quests have been remove from the game so this gameobject (not sure if others) need to be ignored too.

I'll look into this and see what needs despawned
