### ISSUE TITLE
The lost pilot quest giver is a cube

### ISSUE THREAD

**Issue by sadpanda353** [The-Alpha-Project/alpha-core#411]
**Describe the bug**
The npc that give the quest is a cube and have no ''!'' or ''?'' above his head, im pretty sure he got a model since the quest was working well in 0.5.3 (where it got a bug fix see picture)

**Steps to reproduce**
1. go to his position north of Loch modan entrace (Dun morogh side)

**Expected behavior**
NPC should be there instead of the cube and display the ''!'' ''?'' above his head.

**Screenshots**
![PilotQuest](https://user-images.githubusercontent.com/110544187/183290167-2d026c9d-f2b6-4993-a9b8-8b89ee31b6b4.png)

![Source](https://user-images.githubusercontent.com/110544187/183290169-d884ea75-7100-49d5-aae6-2483408a8a84.png)

**Sources**
http://www.bloodwinterclan.com/forums/viewtopic.php?f=102&t=2925&sid=b39d7aa040fb1ea9cc2f41aa8c23e86c

**Comment by GizzleBizzle** [comment]
Found his original model. I think may be a placeholder model aswell since there are 9 DisplayIDs that look identical.
Those are:
- 115
- 312
- 803
- 824
- 826
- 832
- 1764
- 2584
- 3232
Either one should work fine.

Source (From 0.5.5)
![Hammerfoot](https://user-images.githubusercontent.com/111394734/195693083-d8b2afeb-831d-4e8a-8d1c-652bd25b35bf.jpg)
