### ISSUE TITLE
Can't trade with dead players

### ISSUE THREAD

**Issue by GizzleBizzle** [The-Alpha-Project/alpha-core#711]
**Describe the bug**
It isn't possible to trade with dead players. The game doesn't acknowledge a corpse as a valid trade target. Tested in/out of party, up close and from far away.

**Steps to reproduce**
1. Trade a dead player

**Expected behavior**
Living players should be able to trade dead players until patch 0.5.5

**Screenshots**
From official 0.5.5 patchnotes.
![Bez tytułu](https://user-images.githubusercontent.com/111394734/199110804-03e545ff-d4a9-4748-b04e-7234295f31c3.png)

**Video**
https://user-images.githubusercontent.com/111394734/199110595-60fb4cdd-d8ea-4797-963d-47dd0397d7da.mov

**Comment by GrenderG** [comment]
I think this doesn't apply to 0.5.3. Even if I remove the alive check from `CMSG_INITIATE_TRADE`, the trade window will only appear to the player who requested the trade, not to the other player; so you can't finish the trade.

Unless... that was actual Blizzlike bugged behavior in 0.5.3.

**Comment by devw4r** [comment]
> I think this doesn't apply to 0.5.3. Even if I remove the alive check from `CMSG_INITIATE_TRADE`, the trade window will only appear to the player who requested the trade, not to the other player; so you can't finish the trade.
> 
> Unless... that was actual Blizzlike bugged behavior in 0.5.3.

I think its just a misunderstanding of the patch notes, the client itself doesn't allow to trade with a dead player, you can just see that if you click in their portrait, 'Trade' is grayed out, so I think the bug was exactly that, you could do /trade and still pop up a trade window (on the caller) but that doesn't mean you were actually able to trade. So basically, by removing the alive check you get the same behavior that was fixed in 0.5.5
