### ISSUE TITLE
Attacks Always Miss No Matter What

### ISSUE THREAD

**Issue by Daniel3614** [The-Alpha-Project/alpha-core#818]
Killing boars in the Elwynn Forest Vineyards and all my attacks as a level 7 human warrior using a one handed sword with a sword skill of 18, combat maneuvers 30, and rank 2 of both heroic strength and melee finesse. Only ability attacks hit and deal damage - otherwise, all white auto attacks miss.

**Comment by GizzleBizzle** [comment]
That's not a bug. You need higher skill with the weapon You are using in order to hit a mob.

The general formula to start hitting it is about (Moblvl*5) -10, so if the boar is lvl 6, that would mean You need about 20 sword skill in order to hit it... from time to time.

The only attacks that don't miss now are spells and abilities. This is a bug and it's already reported.
