### ISSUE TITLE
TODO: Replace display_id of Clarise Gnarltree

### ISSUE THREAD

**Issue by mindphluxnet** [The-Alpha-Project/alpha-core#912]
Clarise Gnarltree, Blacksmithing trainer in Darkshire, Duskwood needs a proper display_id. Right now's she's a Shane Cube:

![image](https://user-images.githubusercontent.com/4683319/220601722-79a78298-b590-4b7b-ac0f-e542d1b5edca.png)

I've sifted through hundreds of screenshots without avail so there's zero evidence, sadly, but I propose to change her display_id to 93 (or alternatively 752):

![image](https://user-images.githubusercontent.com/4683319/220603208-0ffa3ce5-3b76-4a10-86bf-7904c3e42bed.png)

My reasoning to select that ID is:

- many NPCs in Darkshire still use old models, for example the guy next to her, Morg Gnarltree (242) and outside of the smithy Gavin Gnarltree (191)
- we know she's a female blacksmith. There are not many old model display_ids that look remotely like a blacksmith.
- display_id 93 is also unused
- I find it highly unlikely that *anything* in 0.5.3 was actually still a Shane Cube. This was the first build available to people outside of Blizzard; they'd not wanted to have Shane Cubes everywhere. It even doesn't make sense from a development point of view - the Duskwood zone was mostly complete and itemized, why wouldn't they at least use placeholder old models for NPCs?

Reasoning against using this ID:

- she was created way later than her family members (she has entry 3136 while Morg and Gavin have 226 and 225 respectively)
- for that reason it might be display_id 752 which was created later as well (but has the same visuals for whatever reason)

**Comment by geo-tp** [comment]
![king_day03_1226](https://user-images.githubusercontent.com/72315006/220664050-c316aed0-aade-495d-aaed-7f29e4c8f910.JPG)
![king_day03_1227](https://user-images.githubusercontent.com/72315006/220664065-2d0daf7d-031f-4645-b3a6-22b39c9574e4.JPG)
![130](https://user-images.githubusercontent.com/72315006/220664669-9bc94ff5-1b1a-415d-a0a7-f7d2761ad06d.jpg)


Screenshots from before 0.5.3 where we could probably see Morg Gnarltree and Gavin Gnarltree.

When i reworked darkshire i came to the conclusion that 752 might be the correct display id for Clarise, i didn't change it due to lack of evidence
