### ISSUE TITLE
TODO: Figure out Cursed Sailor/Marine's DisplayID

### ISSUE THREAD

**Issue by Yushe** [The-Alpha-Project/alpha-core#976]
After trying to track down alpha footage that I saw for issue #975 I stumbled upon a discovery that we got the Display IDs for Cursed Sailor/Marine's wrong.

This footage of 0.5.3 shows what one of these NPCs should look like (most likely Cursed Sailor).
Because of how blurry the footage is its almost impossible to know which NPC it is.

The video in question: https://www.youtube.com/watch?v=LirXh6fBeqU
The NPC is seen at 16:05

_**Side note:**_
I am unsure if this full presentation video of 0.5.3 is archived or if we know the origin of it.

![cursed marine](https://user-images.githubusercontent.com/10089856/225168689-8df81e84-1660-4a65-9039-1d1e759f3a21.png)

**Comment by geo-tp** [comment]
Cursed sailor display_id is 3505, same as vanilla.
Cursed marine display_id was missing and was changed to use 3507 because of screenshot below

(notice name of the file : "05 12 04 turned into a cursed marine")
![05-12-04 Turned Into A Cursed Marine](https://user-images.githubusercontent.com/72315006/225171139-d9a793c2-5d42-4fbc-bdf7-2c0b1a224d20.jpg)

both display id are very close
![Capture d’écran_2022-12-19_19-42-02](https://user-images.githubusercontent.com/72315006/225171076-951ee42d-26c5-49d9-be11-bb20b5ef9bcc.png)

Are we sure screenshot from gamemeca is from version 0.5.3 ?

**Comment by geo-tp** [comment]
Probably the build that we see in video is not 0.5.3

Here's a screenshot from the video (notice red thing on screen when someone take a picture)
![Capture d’écran_2023-03-16_19-58-50](https://user-images.githubusercontent.com/72315006/225726320-b7897910-3b3b-47ca-bfe7-2bc5f1b39ba7.png)

Here's probably a screenshot taken the same day showing Undercity (notice red think on screen as well)
![Capture d’écran_2023-03-16_19-56-42](https://user-images.githubusercontent.com/72315006/225726506-c279a25d-b66d-483b-a77e-ef48ade1c129.png)

On the same video showing Undercity, we can see there is no liquid yet, 0.5.3 have liquid
![Capture d’écran_2023-03-16_19-55-33](https://user-images.githubusercontent.com/72315006/225726581-981f4484-542f-4a7a-85f8-55808ac9eced.png)


Probably this build is earlier than 0.5.3

**Comment by Yushe** [comment]
The build in the footage is confirmed to be 32 days older than the build that we have but it is still 0.5.3.
